### ISSUE TITLE
Updating github repositories with the logged key

### ISSUE THREAD

**Issue by evilensky** [CircleCI-Public/github-ssh-regeneration#3]
Hello,
Is there functionality to update the keys on the Github repository side also?  Thank you.

**Comment by nbialostosky** [comment]
Hi @evilensky !

Great question -- if you actually utilize this script (and just in general when you generate a new deploy or user key from CircleCI) we create the corresponding keypair within GitHub automatically, we have the private key and GitHub has the public key.

We have some additional details here:

https://circleci.com/docs/2.0/gh-bb-integration/#deployment-keys-and-user-keys

Does that help answer your question?

**Comment by evilensky** [comment]
Absolutely, thank you so much for the quick response!
