### ISSUE TITLE
Project shows up in project_names, but is not found when making `checkout-key` call

### ISSUE THREAD

**Issue by evilensky** [CircleCI-Public/github-ssh-regeneration#5]
Hello I would just like to confirm that it is possible for a project to be listed in the list of projects, but to then result in a Not Found error when the call to `https://circleci.com/api/v2/project/github/{org}/{project}/checkout-key` is made? We should probably Except not found errors if this is a possibility.

Or should I consider this an error with our organization and open a support case?

Thank you,

**Comment by zetta** [comment]
I have the same edge case for some old projects/repositories in my org, I've commented the `raise` and instead print the error for debugging purposes and add a `continue`
